/* Hand-authored, not generated by `supabase gen types` — there is no live
   project to generate against yet (M7 was explicitly scoped as
   "scaffold only, no live project" by the user). Kept in lockstep by hand
   with supabase/migrations/*.sql as each phase adds tables/functions;
   Phase 9's docs note this as the one thing a real provisioning pass
   should immediately replace with a generated file, since a hand-authored
   type can drift from the real schema in a way a generated one can't.

   Row/Insert/Update follow supabase-js's own generated-type convention:
   Row is exactly what a select returns; Insert omits columns with a
   database default (`id`, timestamps, status defaults, ...) as optional;
   Update makes every column optional. */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type QuestStatusRow =
  | "draft"
  | "open"
  | "assigned"
  | "in_progress"
  | "completed"
  | "paid"
  | "cancelled"
  | "expired"
  | "disputed";

export type OfferStatusRow = "pending" | "accepted" | "declined" | "withdrawn" | "expired";

export type LedgerAccountRow = "user_available" | "user_held" | "platform_escrow" | "platform_fee" | "external_bank";

export type PaymentKindRow = "deposit" | "cashout";
export type PaymentStateRow = "pending" | "succeeded" | "failed";

export type NotificationTypeRow =
  | "offer_received"
  | "offer_accepted"
  | "offer_declined"
  | "quest_started"
  | "quest_done"
  | "quest_cancelled"
  | "quest_disputed"
  | "quest_expired"
  | "payment"
  | "message";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          rating: number;
          quests_completed: number;
          verified: boolean;
          area: string;
          home_x: number;
          home_y: number;
          cancel_rate: number;
          bio: string;
          phone: string;
          email: string;
          bank: string;
          joined: string;
        };
        Insert: {
          id: string;
          name: string;
          area: string;
          home_x: number;
          home_y: number;
          rating?: number;
          quests_completed?: number;
          verified?: boolean;
          cancel_rate?: number;
          bio?: string;
          phone?: string;
          email?: string;
          bank?: string;
          joined?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      categories: {
        Row: { id: string; label: string };
        Insert: { id: string; label: string };
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
      };
      areas: {
        Row: { name: string; point_x: number; point_y: number };
        Insert: { name: string; point_x: number; point_y: number };
        Update: Partial<Database["public"]["Tables"]["areas"]["Insert"]>;
      };
      quests: {
        Row: {
          id: string;
          poster_id: string;
          title: string;
          payout_minor: number;
          payout_unit: "fixed";
          category_id: string;
          point_x: number;
          point_y: number;
          location: unknown;
          estimated_minutes: number;
          duration_label: string | null;
          scheduled_for: string;
          expires_at: string;
          created_at: string;
          status: QuestStatusRow;
          accepted_offer_id: string | null;
          address_line: string;
          area: string;
          details: string;
          requirements: string[];
          started_at: string | null;
          completed_at: string | null;
          paid_at: string | null;
          cancelled_at: string | null;
          cancelled_by: string | null;
          cancel_reason: string | null;
          disputed_at: string | null;
          dispute_reason: string | null;
        };
        Insert: {
          poster_id: string;
          title: string;
          payout_minor: number;
          category_id: string;
          point_x: number;
          point_y: number;
          estimated_minutes: number;
          duration_label?: string | null;
          scheduled_for: string;
          expires_at: string;
          address_line: string;
          area: string;
          details?: string;
          requirements?: string[];
          status?: QuestStatusRow;
        };
        Update: Partial<Database["public"]["Tables"]["quests"]["Row"]>;
      };
      offers: {
        Row: {
          id: string;
          quest_id: string;
          doer_id: string;
          amount_minor: number;
          status: OfferStatusRow;
          note: string;
          created_at: string;
          responded_at: string | null;
        };
        Insert: {
          quest_id: string;
          doer_id: string;
          amount_minor: number;
          note?: string;
          status?: OfferStatusRow;
        };
        Update: Partial<Database["public"]["Tables"]["offers"]["Row"]>;
      };
      threads: {
        Row: {
          id: string;
          quest_id: string;
          poster_id: string;
          doer_id: string;
          last_message_at: string;
        };
        Insert: { quest_id: string; poster_id: string; doer_id: string; last_message_at?: string };
        Update: Partial<Database["public"]["Tables"]["threads"]["Row"]>;
      };
      messages: {
        Row: { id: string; thread_id: string; sender_id: string; body: string; at: string };
        Insert: { thread_id: string; sender_id: string; body: string };
        Update: Partial<Database["public"]["Tables"]["messages"]["Row"]>;
      };
      thread_read_at: {
        Row: { user_id: string; thread_id: string; read_at: string };
        Insert: { user_id: string; thread_id: string; read_at?: string };
        Update: Partial<Database["public"]["Tables"]["thread_read_at"]["Row"]>;
      };
      saved_quests: {
        Row: { user_id: string; quest_id: string; created_at: string };
        Insert: { user_id: string; quest_id: string };
        Update: Partial<Database["public"]["Tables"]["saved_quests"]["Row"]>;
      };
      ledger_entries: {
        Row: {
          id: string;
          txn_id: string;
          account: LedgerAccountRow;
          user_id: string | null;
          quest_id: string | null;
          amount_minor: number;
          at: string;
          memo: string;
        };
        Insert: {
          txn_id: string;
          account: LedgerAccountRow;
          user_id?: string | null;
          quest_id?: string | null;
          amount_minor: number;
          memo?: string;
        };
        Update: Partial<Database["public"]["Tables"]["ledger_entries"]["Row"]>;
      };
      payments: {
        Row: {
          id: string;
          txn_id: string;
          kind: PaymentKindRow;
          user_id: string;
          amount_minor: number;
          state: PaymentStateRow;
          provider: "simulated";
          provider_id: string;
          created_at: string;
          settled_at: string | null;
        };
        Insert: {
          txn_id: string;
          kind: PaymentKindRow;
          user_id: string;
          amount_minor: number;
          provider_id: string;
          state?: PaymentStateRow;
        };
        Update: Partial<Database["public"]["Tables"]["payments"]["Row"]>;
      };
      reviews: {
        Row: {
          id: string;
          quest_id: string;
          rater_id: string;
          ratee_id: string;
          rating: number;
          comment: string;
          at: string;
        };
        Insert: {
          quest_id: string;
          rater_id: string;
          ratee_id: string;
          rating: number;
          comment?: string;
        };
        Update: Partial<Database["public"]["Tables"]["reviews"]["Row"]>;
      };
      reports: {
        Row: { id: string; reporter_id: string; target_user_id: string; reason: string; at: string };
        Insert: { reporter_id: string; target_user_id: string; reason: string };
        Update: Partial<Database["public"]["Tables"]["reports"]["Row"]>;
      };
      blocked_users: {
        Row: { user_id: string; blocked_id: string; created_at: string };
        Insert: { user_id: string; blocked_id: string };
        Update: Partial<Database["public"]["Tables"]["blocked_users"]["Row"]>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: NotificationTypeRow;
          quest_id: string | null;
          body: string;
          at: string;
          read_at: string | null;
        };
        Insert: {
          user_id: string;
          type: NotificationTypeRow;
          quest_id?: string | null;
          body: string;
          read_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["notifications"]["Row"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      quest_status: QuestStatusRow;
      offer_status: OfferStatusRow;
      ledger_account: LedgerAccountRow;
      payment_kind: PaymentKindRow;
      payment_state: PaymentStateRow;
      notification_type: NotificationTypeRow;
    };
  };
}
