/* Hand-authored, not generated by `supabase gen types` — there is no live
   project to generate against yet (M7 was explicitly scoped as
   "scaffold only, no live project" by the user). Kept in lockstep by hand
   with supabase/migrations/*.sql as each phase adds tables/functions.

   Deliberately NOT plugged into createClient<Database>() as
   supabase-js's schema generic (client.ts uses a plain, untyped
   createClient()) — postgrest-js's generic select-string parser expects
   a full generated schema (every table's `Relationships` array, every
   RPC's `Args`/`Returns`/`SetofOptions`, embedded-resource metadata) to
   resolve real types; hand-maintaining that faithfully by hand across
   nine phases, for a schema that has never run against a live project to
   verify it against, would be fragile ceremony with no real payoff. Each
   adapters/supabase/*.ts file instead defines the *Row interfaces it
   needs (mirroring the tables below) and casts its own query results —
   the same "trust the shape, verify it once there's a real project"
   posture the rest of this scaffold takes. Phase 9's docs note this file
   as the first thing a real provisioning pass should replace with a
   generated one, at which point the createClient<Database> generic
   becomes worth wiring back in. */
export type QuestStatusRow =
  | "draft"
  | "open"
  | "assigned"
  | "in_progress"
  | "completed"
  | "paid"
  | "cancelled"
  | "expired"
  | "disputed";

export type OfferStatusRow = "pending" | "accepted" | "declined" | "withdrawn" | "expired";

export type LedgerAccountRow = "user_available" | "user_held" | "platform_escrow" | "platform_fee" | "external_bank";

export type PaymentKindRow = "deposit" | "cashout";
export type PaymentStateRow = "pending" | "succeeded" | "failed";

export type NotificationTypeRow =
  | "offer_received"
  | "offer_accepted"
  | "offer_declined"
  | "quest_started"
  | "quest_done"
  | "quest_cancelled"
  | "quest_disputed"
  | "quest_expired"
  | "payment"
  | "message";

export interface ProfileRow {
  id: string;
  name: string;
  rating: number;
  quests_completed: number;
  verified: boolean;
  area: string;
  home_x: number;
  home_y: number;
  cancel_rate: number;
  bio: string;
  phone: string;
  email: string;
  bank: string;
  joined: string;
  avatar_url: string | null;
}

export interface CategoryRow {
  id: string;
  label: string;
}

export interface AreaRow {
  name: string;
  point_x: number;
  point_y: number;
}

export interface QuestRow {
  id: string;
  poster_id: string;
  title: string;
  payout_minor: number;
  payout_unit: "fixed";
  category_id: string;
  point_x: number;
  point_y: number;
  estimated_minutes: number;
  duration_label: string | null;
  scheduled_for: string;
  expires_at: string;
  created_at: string;
  status: QuestStatusRow;
  accepted_offer_id: string | null;
  address_line: string;
  area: string;
  details: string;
  requirements: string[];
  started_at: string | null;
  completed_at: string | null;
  paid_at: string | null;
  cancelled_at: string | null;
  cancelled_by: string | null;
  cancel_reason: string | null;
  disputed_at: string | null;
  dispute_reason: string | null;
}

export interface OfferRow {
  id: string;
  quest_id: string;
  doer_id: string;
  amount_minor: number;
  status: OfferStatusRow;
  note: string;
  created_at: string;
  responded_at: string | null;
}

export interface ThreadRow {
  id: string;
  quest_id: string;
  poster_id: string;
  doer_id: string;
  last_message_at: string;
}

export interface MessageRow {
  id: string;
  thread_id: string;
  sender_id: string;
  body: string;
  at: string;
}

export interface LedgerEntryRow {
  id: string;
  txn_id: string;
  account: LedgerAccountRow;
  user_id: string | null;
  quest_id: string | null;
  amount_minor: number;
  at: string;
  memo: string;
}

export interface PaymentRow {
  id: string;
  txn_id: string;
  kind: PaymentKindRow;
  user_id: string;
  amount_minor: number;
  state: PaymentStateRow;
  provider: "simulated";
  provider_id: string;
  created_at: string;
  settled_at: string | null;
}

export interface ReviewRow {
  id: string;
  quest_id: string;
  rater_id: string;
  ratee_id: string;
  rating: number;
  comment: string;
  at: string;
}

export interface ReportRow {
  id: string;
  reporter_id: string;
  target_user_id: string;
  reason: string;
  at: string;
}

export interface NotificationRow {
  id: string;
  user_id: string;
  type: NotificationTypeRow;
  quest_id: string | null;
  body: string;
  at: string;
  read_at: string | null;
}
