/* GENERATED by scripts/gen-tokens.ts from preview/tokens/*.css — do not
   hand-edit. Regenerate with `npm run tokens:gen`. This file IS the
   canonical source from here on (ADR-002) — the script's other job is
   `npm run tokens:check`, a CI drift gate against this exact content. */

export const semantic = {
  color: {
    text: {
      primary: "#14150f",
      secondary: "#5c5f50",
      muted: "#7b7e6d",
      disabled: "#9a9c8d",
      inverse: "#fbfaf4",
      link: "#14150f",
      danger: "#c02c1e",
      success: "#12875a",
    },
    surface: {
      page: "#f4f2e8",
      card: "#ffffff",
      raised: "#fbfaf4",
      sunken: "#eae7d8",
      inverse: "#14150f",
      accent: "#c6f24e",
      accentSoft: "#e9fcb8",
      money: "#ffc53d",
      moneySoft: "#ffecc2",
      hot: "#ff5a2b",
      hotSoft: "#ffd4c4",
      overlay: "rgba(20,21,15,.44)",
    },
    border: {
      strong: "#14150f",
      default: "#c9cbbc",
      subtle: "#e4e5da",
    },
    focusRing: {
      ring: "#14150f",
      halo: "#c6f24e",
    },
    action: {
      primary: {
        bg: "#c6f24e",
        bgHover: "#aedc30",
        bgActive: "#8fbd18",
        fg: "#14150f",
      },
      secondary: {
        bg: "#ffffff",
        bgHover: "#f4f2e8",
        fg: "#14150f",
      },
      inverse: {
        bg: "#14150f",
        bgHover: "#2e3026",
        fg: "#fbfaf4",
      },
      danger: {
        bg: "#de3b2b",
        fg: "#ffffff",
      },
      disabled: {
        bg: "#e4e5da",
        fg: "#9a9c8d",
      },
    },
  },
  stroke: {
    ink: {
      width: 1.5,
      color: "#14150f",
    },
    soft: {
      width: 1,
      color: "#c9cbbc",
    },
  },
  shadow: {
    stickerSm: {
      dx: 2,
      dy: 2,
      color: "#14150f",
    },
    sticker: {
      dx: 3,
      dy: 3,
      color: "#14150f",
    },
    stickerLg: {
      dx: 5,
      dy: 5,
      color: "#14150f",
    },
    stickerLime: {
      dx: 3,
      dy: 3,
      color: "#8fbd18",
    },
    pressed: {
      dx: 1,
      dy: 1,
      color: "#14150f",
    },
    soft: {
      offsetX: 0,
      offsetY: 6,
      blur: 18,
      spread: -8,
      color: "#14150f",
      opacity: 0.24,
      inset: false,
    },
    overlay: {
      offsetX: 0,
      offsetY: 24,
      blur: 48,
      spread: -16,
      color: "#14150f",
      opacity: 0.38,
      inset: false,
    },
    insetField: {
      offsetX: 0,
      offsetY: 1,
      blur: 0,
      spread: 0,
      color: "#14150f",
      opacity: 0.06,
      inset: true,
    },
  },
  elevation: {
    flat: null,
    card: "sticker",
    raised: "stickerLg",
    float: "soft",
    modal: "overlay",
  },
} as const;
