/* GENERATED by scripts/gen-tokens.ts from preview/tokens/*.css — do not
   hand-edit. Regenerate with `npm run tokens:gen`. This file IS the
   canonical source from here on (ADR-002) — the script's other job is
   `npm run tokens:check`, a CI drift gate against this exact content. */

export const type = {
  display: {
    fontFamily: "BricolageGrotesque_800ExtraBold",
    fontSize: 48,
    lineHeight: 50,
    letterSpacing: -1.44,
  },
  title: {
    fontFamily: "BricolageGrotesque_700Bold",
    fontSize: 24,
    lineHeight: 28,
    letterSpacing: -0.36,
  },
  body: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 16,
    lineHeight: 23,
  },
  label: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 15,
  },
  caps: {
    fontFamily: "InstrumentSans_700Bold",
    fontSize: 12,
    letterSpacing: 1.08,
  },
  money: {
    fontFamily: "BricolageGrotesque_800ExtraBold",
    fontVariant: [
      "tabular-nums",
    ],
  },
} as const;
